name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Wait for 30 minutes
        run: |
          sleep 30m

      - uses: vedantmgoyal2009/winget-releaser@main
        with:
          identifier: ONLYOFFICE.DesktopEditors
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}

